# Generated by Django 5.0.3 on 2024-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_race_start_date_race_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='timer_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='timer_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
