# Generated by Django 5.0 on 2024-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_race_timer_end_race_timer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='timer_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='timer_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
