# Generated by Django 4.2.5 on 2024-03-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_race_timer_end_race_timer_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='team1_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='team2_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='timer_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='timer_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teamLogos/'),
        ),
    ]
